name: Get Fingerprint

on:
  workflow_dispatch:

jobs:
  fingerprint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Java
        run: sudo apt-get install -y openjdk-17-jdk

      - name: Generate Keystore
        run: |
          keytool -genkey -v \
            -keystore jan-aawaz.keystore \
            -alias jan-aawaz \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Jan Aawaz, OU=App, O=JanAawaz, L=Delhi, S=Delhi, C=IN" \
            -storepass janaawaz123 \
            -keypass janaawaz123

      - name: Get SHA1 Fingerprint
        run: |
          keytool -keystore jan-aawaz.keystore \
            -list -v \
            -storepass janaawaz123

      - name: Upload Keystore
        uses: actions/upload-artifact@v4
        with:
          name: keystore-file
          path: jan-aawaz.keystore
