name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore File
        run: |
          sudo apt-get install -y openjdk-17-jdk
          keytool -genkey -v \
            -keystore jan-aawaz.keystore \
            -alias jan-aawaz \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Jan Aawaz, OU=App, O=JanAawaz, L=Delhi, S=Delhi, C=IN" \
            -storepass janaawaz123 \
            -keypass janaawaz123
          echo "SHA1:"
          keytool -list -v \
            -keystore jan-aawaz.keystore \
            -storepass janaawaz123 | grep "SHA1:"

      - name: Upload as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jan-aawaz-keystore
          path: jan-aawaz.keystore
